allowBuilds:
  "@google/genai": true
  protobufjs: true
  sharp: true
  unrs-resolver: true

engineStrict: true
nodeLinker: hoisted
nodeVersion: 24.18.0
overrides:
  postcss: 8.5.12
  sharp: 0.35.3
savePrefix: ""
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
